# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170927_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='product_subcategory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Subcategory'),
        ),
    ]
